/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.gradleup.shadow") version "9.0.0-beta11"
    id("io.papermc.paperweight.userdev") version "1.7.5"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://oss.sonatype.org/content/groups/public/")
    maven("https://mvn.lumine.io/repository/maven-public/")
    maven("https://repo.onarandombox.com/content/groups/public/")
    maven("https://maven.enginehub.org/repo/")
    maven("https://repo.azisaba.net/repository/maven-public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
    compileOnlyApi("io.lumine:Mythic-Dist:5.7.2")
    compileOnlyApi("com.onarandombox.multiversecore:multiverse-core:4.3.12")
    compileOnlyApi("com.sk89q.worldguard:worldguard-bukkit:7.0.12")
    @Suppress("VulnerableLibrariesLocal", "RedundantSuppression")
    compileOnlyApi("net.azisaba.loreeditor:plugin:1.2.0:all")

    implementation("com.zaxxer:HikariCP:6.0.0")
    implementation("org.mariadb.jdbc:mariadb-java-client:3.5.3")

    paperweight.paperDevBundle("1.21.1-R0.1-SNAPSHOT")
}

group = "com.github.azuazu3939"
version = "2.2.0"
description = "AzPlugin"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks {
    compileJava {
        options.encoding = Charsets.UTF_8.name()
    }
    shadowJar {
        relocate("com.zaxxer.hikari", "com.github.azuazu3939.lib.com.zaxxer.hikari")
        relocate("org.mariadb.jdbc", "com.github.azuazu3939.lib.org.mariadb.jdbc")
    }
}
