Colors:
  RED: "§c§l"
  BLUE: "§9§l"
  GREEN: "§a§l"
  YELLOW: "§e§l"

Database:
  #jdbc:mariadb
  scheme: jdbc:mysql
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  break: break
  interact: interact
  inventory: inventory
  place: place
  edit: edit
  drop: drop
