name: AzPlugin
version: '2.2.0'
main: com.github.azuazu3939.azPlugin.AzPlugin
api-version: '1.21'
authors: [ MCLove32 ]

depend:
  - MythicMobs
  - Multiverse-Core
  - WorldGuard
  - LoreEditor

commands:
  worldregen:
    permission: azplugin.command.worldregen
    aliases:
      - wr
      - worldRegen
  worldcreate:
    permission: azplugin.command.worldcreate
    aliases:
      - wc
      - worldCreate
  worldteleport:
    permission: azplugin.command.worldteleport
    aliases:
      - wt
      - worldTeleport
      - wsp
      - ws
  worldset:
    permission: azplugin.command.worldset
    aliases:
      - wset
      - wse
      - wst
  mode:
    permission: azplugin.command.mode
    aliases:
      - md
  setmana:
    permission: azplugin.command.setmana
    aliases:
      - addmana
      - addMana
      - setMana
      - sm
  setmaxmana:
    permission: azplugin.command.setmaxmana
    aliases:
      - smm
  dungeon:
    permission: azplugin.command.dungeon
    aliases:
      - dg
  viewer:
    permission: azplugin.command.viewer
    aliases:
      - vie
  //pos1:
    permission: azplugin.command.pos1
    aliases:
      - /apos1
      - apos1
  //pos2:
    permission: azplugin.command.pos2
    aliases:
      - /apos2
      - apos2
  //setItemStack:
    permission: azplugin.command.setitemdrop
    aliases:
      - //setdrop
      - /asetitem
      - /asetdrop
      - asetitem
      - asetdrop
  //setShop:
    permission: azplugin.command.setshop
    aliases:
      - asetshop
      - /asetshop
  //ctrl:
    permission: azplugin.command.ctrl
    aliases:
      - /ctrl
      - ctrl


permissions:
  azplugin.*:
    default: false
    children:
      azplugin.reload.mythicmobs: true
      azplugin.command.*: true
  azplugin.command.*:
    default: false
    children:
      azplugin.command.setmaxmana: true
      azplugin.command.setmana: true
      azplugin.command.mode: true
      azplugin.command.worldset: true
      azplugin.command.worldteleport: true
      azplugin.command.worldcreate: true
      azplugin.command.worldregen: true
      azplugin.command.dungeon: true
      azplugin.command.viewer: true
      azplugin.command.pos1: true
      azplugin.command.pos2: true
      azplugin.command.setitemdrop: true
      azplugin.command.setshop: true
      azplugin.command.ctrl: true
  azplugin.reload.mythicmobs:
    default: op
  azplugin.command.setmaxmana:
    default: op
  azplugin.command.setmana:
    default: op
  azplugin.command.mode:
    default: op
  azplugin.command.worldset:
    default: op
  azplugin.command.worldteleport:
    default: op
  azplugin.command.worldcreate:
    default: op
  azplugin.command.worldregen:
    default: op
  azplugin.command.dungeon:
    default: op
  azplugin.command.viewer:
    default: true
  azplugin.command.pos1:
    default: op
  azplugin.command.pos2:
    default: op
  azplugin.command.ctrl:
    default: op